### ISSUE TITLE
log_oddsDE = -nan

### ISSUE THREAD

**Issue by Niveda-S** [mapDIA/mapDIA#2]
Hi,
We are encountering a scenario where the FDR is 0 (which I assume is considered significant) but we also see that the log_oddsDE is -nan and the score is 0 for comparative analysis
![image](https://user-images.githubusercontent.com/17713621/170319206-8de52532-cbb3-4d18-bfa4-f47d500f5773.png)

What do these imply? Should we be discarding these proteins as "not significant change"?

Thanks!

**Comment by guoshou** [comment]
your data has probably too much missing data, impute the zeros in your input table with "1" and run again.
